import type { Metadata } from 'next'
import { Providers } from '@/app/providers'
import { ColorModeScript, Box } from '@chakra-ui/react'
import theme from '@/utils/theme'
import { Navbar } from '@/app/components/Navbar';
import { Footer } from '@/app/components/Footer';

export const metadata: Metadata = {
  title: 'SSUJoon',
  description: 'Generated by create next app',
};

// TODO: Add colorModeManager to fix flashing (reference: https://v2.chakra-ui.com/docs/styled-system/color-mode#add-colormodemanager-optional-for-ssr)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode}></ColorModeScript>
        <Providers>
          <Box minH='100vh'>
            <Navbar />
            <Box margin={6}>
              {children}
            </Box>
          </Box>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
